### ISSUE TITLE
Figure out strategy for reloading inline JS changes

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#105]
First reported by @KeniMorri, and confirmed by @K-LV and me, Brackets won't reload inline javascript on changes to an HTML file. According to [their docs](https://github.com/adobe/brackets/wiki/Troubleshooting#css-html-and-javascript) (see final bullet), you have to manually reload for inline JS changes to show in live preview.

<blockquote>For JavaScript and other external file types, when you save your changes, the page is reloaded to reflect your changes.<em> For embedded JS, you will need to reload browser.</em></blockquote> 

We are going to have to figure out a few things here:
* how to signal this to the user, who won't understand why their changes aren't updating
* how to do the update, whether via some manual action by the user (requires UI), or whether we do it automatically somehow?

**Comment by sedge** [comment]
Thimble has a reload button already, so the tricky part would be how to force the reload in a clean manner. I'm not confident this can happen without changes to brackets code.

**Comment by humphd** [comment]
What we need to know is if there is some way to determine in the preview document/DOM (i.e., via messages from over the postMessage transport/protocol) when updates have stopped.  If we were alerted via a message in the live dev protocol, we could somehow update the UI in the preview to show the user they need to do something (e.g., put a gray filter of the page with a Reload button in the middle or something).

Can someone figure this out?

**Comment by sedge** [comment]
Sounds like a job for the sedgehammer!

**Comment by humphd** [comment]
I did a bit of digging.  The issue here is not with Brackets, as such, but the browser.  As you type more in the script tag's body, the protocol does update the preview side with that new content.  However, once a script is loaded by the browser, it won't re-parse it just because it changes.

Maybe we need some kind of way to track changes to the script elements as we change them?

**Comment by humphd** [comment]
Here's what happens when we add a new script tag to the editor on the other side of the live dev protocol (i.e., this is what gets received in the preview iframe via the protocol):

```
[Brackets LiveDev] msg Object {
  id: 4,
  method: "Runtime.evaluate",
  params: Object,
  expression: "_LD.applyDOMEdits([{"type":"textReplace","content":"\n    ","parentID":5,"beforeID":6},{"type":"elementInsert","tag":"script","tagID":13,"parentID":5,"attributes":{},"beforeID":6},{"type":"textInsert","content":"\n    ","parentID":5,"afterID":13,"beforeID":6}])"
}
```
As you can see, it knows that it's inserting a `script` tag.  Maybe that provides us a way to add some extra code to watch for changes to it?

**Comment by humphd** [comment]
@busykai, @sebaslv I wonder if you have any advice here.  Basically, what I'm looking for is a Live Dev flow like so:
* User has an HTML document in the editor, and iframe-based MultiBrowser LiveDev preview open (what our fork does, basically)
* User adds an inline script element to the document in the editor
* The remote protocol applies this DOM update, and also sets up some kind of listener on the script element
* The user types some new JS into the inline script element, and changes are sent over to the preview to be added
* The remote DOM again applies the changes (e.g., adds more content to the script element's textNode) and also triggers some event in the remote page to indicate that the page needs a reload.
* The remote iframe preview changes somehow (maybe a new button is added, or a door-hanger drops down from the top saying a reload is needed to see JS updates).

What mechanism in the Live Dev stuff can I hook into to accomplish this?

**Comment by humphd** [comment]
We're not going to have a solution for this by Friday, so I'm moving out of this milestone.

**Comment by gideonthomas** [comment]
This *can* be an upstream change. Before calculating the DOMDiff, instead of calculating a diff for anything inside a `<script>` tag, we can make it so that if anything inside the `<script>` tag changes, we generate a diff that represents the entire `<script>` tag. This would mean that we'd have to change the code that generates the new id's for every DOM element change, to change the id of the `<script>` tag inside which changes occurred (so that the diff is calculated for the whole script and not just the change inside the script).

This may not be the best solution (not even sure if its possible) but its just a thought.

**Comment by humphd** [comment]
Short of advice from our Brackets friends, I wonder if it's worth doing an experiment here.  We'd have to be careful to separate changes to a `script` element that points to an external resource (e.g., has `src`) vs. one where we're changing its text content.

**Comment by sedge** [comment]
I like Gideon's idea. I'll give it a spin.

**Comment by sedge** [comment]
This is up for grabs again.

**Comment by busykai** [comment]
@humphd, I was away hence the delay. The solution you're suggesting seems OK with exception that DOM updates are not needed when the page is reloading -- it will get fresh current copy of the content of the editor. Since reload is an "expensive" operation, it should be done in limited amount of circumstances, e.g. when there's a copy-paste (and the resulting document is syntactically correct); when cursor is repositioned (in the editor) from script tag to non-javascript location in the html and so on. While theoretically, the script edits could be injected, it will never be semantically correct (because of the current app state, new event handlers for the past events etc.). I'm interested in covering these cases in the mainstream Brackets (and XDK as well), so I have to plan to invest some cycles into this.

If I recall it right, so far we never refresh after DOM diff is done. The same technique needs to be applied to properly fix #10634 (copy-pasting entire document). Even when successful, we should not assume any difference could be resolved by modifying remote DOM (in case of #10634 it's trying to replacing the root element, `<html>`, of the document; in this case it's inserting a `<script>` tag into the loaded document). It's safer and proper to handle such corner cases by reloading the page (the major downside of this is loosing the page state if there was any, could be really annoying to have to constantly recover it).

**Comment by humphd** [comment]
So auto-reloading is one solution, but I get that it's expensive.  What about just making it clear to the user that the preview DOM is now out of sync, and a reload will be required to get the scripts to the same place as the editor?  This could be done with UI in the preview.  Then it's on the user to do the reload when it makes sense.  In addition, you could have a pref to auto-reload in this case, so it's possible to have it work both ways.

**Comment by busykai** [comment]
Yeah, it can be done either way (UI indication or auto-reload). These are actions, however. My point is being we're not detecting the conditions for the action.

I am favoring auto-reload because, while being expensive, it is more explicit and straightforward. UI indication, in my experience, however clever, will result in some folks wondering what's going on (as it would require to understand the why) and ultimately can only be solved by reloading. We could have an option to decide which action should be taken. Different environments may decide on the reasonable default, as per requirements.

**Comment by humphd** [comment]
OK, I'm with you now.  Yes, I'd favour automatic intervention vs. clever UI for this, too.

So should this get filed upstream?  How are we going to move it forward?  This is already a blocker for us.

**Comment by busykai** [comment]
I have filed adobe/brackets#5656 which is more or less covers editing existing tag, but does not treat the paste usecase. I have couple of free days ahead, let me draft something, at least to estimate the complexity of the change. Since it's a blocking issue for you, I will put more priority to it.

**Comment by humphd** [comment]
@busykai++

**Comment by humphd** [comment]
As an aside, https://github.com/Matt-Esch/virtual-dom is interesting.

**Comment by busykai** [comment]
@humphd, thanks for the reference! i'll take a look at it. so far we hadn't problems with out version of virtual DOM. the real trick is how to translate to edits to DOM to DOM modifications on the remote.

at any rate, if you merge both `kai/fix-5656-live-dev` and `kai/fix-10821-ld-allow-reload-in-browser` from `adobe/brackets`, you should get a working version which reloads the browser when there are "non-reconcilable" edits to the HTML document being previewed. It has a couple of issues now: 1) preview page is jiggling when reloads, it's due to the fact that any reload of the page is taken as regular close/open; 2) *any edit*, even just 1 char, of an embedded `<script>` causes a reload, this needs to be addressed by introducing "pending reload" which will be done when cursor is repositioned somewhere else. I will deal with these two later in `kai/fix-5656-live-dev` (which is currently not a PR due to these issues). I'd appreciate though if try it out and let me know if it works with your transport/server and help identifying more issues or cases that are not covered.

**Comment by humphd** [comment]
I tried merging these two branches onto our stuff (and also reverted the copy-paste fix we applied locally, see https://github.com/humphd/brackets/commits/revert-copy-paste-fix).  I can see that it's reloading all the time now, as expected; however, it's not changing the contents of the preview.  Even simple HTML edits cause a reload, but don't show up in the preview.

This might be due to how we do our browser-based web server, so I want to spend some time on this next week (it's a long weekend here right now) before I say that your stuff isn't working.  Are you ever on irc?  On Monday I'll dig into this properly.

Thanks for pushing on this for us, it's really appreciated.

**Comment by humphd** [comment]
BTW, in case one of my guys wants to look at this, I put all the work up at https://github.com/humphd/brackets/tree/issue105-revert-copy-paste.

**Comment by busykai** [comment]
ooops. sorry about reloading all the time, my bad. haven't checked the draft fix after fixing the reload issue. please merge `kai/fix-5656-live-dev` once again.

**Comment by humphd** [comment]
I've remerged, thanks for the extra fix.  You can play with it here:

http://humphd.github.io/brackets/dist/

I think it's mostly working, but there are some odd things.  First, any change to a top-level child of the `html` element will now cause a reload, e.g., if I add a newline before/after an existing element like the `p` tag.  This isn't horrible, but it's more churn than necessary, I think.  The check for `oldNode` being `html` means that lots of changes end-up causing a reload.

The stranger issue I'm seeing is that reloads for JS updates are lagging somehow, and things get out of sync for a while.  My current theory is that this is still related to our code, but I need more time to go further.  You can see what I mean if you try and put a script into the `body` of the page.  When it reloads, it will revert the page back to the original URL we gave it when the editor was first opened--I don't know how it remembers this URL, since we are generating new blob URL Objects all the time (I have confirmed that all this code of ours is working).  It's almost like it has cached the first URL in a variable somewhere in LiveDev, or maybe it reads it off an outdated attribute in the DOM; I'm unclear how it's possible, but I've confirmed it.

Eventually, if you make enough changes in the editor, and it generates enough blob URL Objects and reloads the iframe enough, you'll get your scripts running.  Try putting a few `alert()`s inside various scripts and you'll see that eventually they will fire.  But it takes time, and many reloads, which I don't understand, and need to investigate further.

@busykai I'll give you an update again in a day or so, after I figure out what's happening.  I think we're close, though.  Nice work.

**Comment by humphd** [comment]
I think I found the reload issue, fix is in https://github.com/humphd/brackets-browser-livedev/pull/49

I've updated http://humphd.github.io/brackets/dist/ with that fix, too, and it works well in Chrome/Safari.  Firefox seems to still get behind and need more changes to reload and catch up.

**Comment by humphd** [comment]
The work by @K-LV and @gideonthomas to make reloads happen correctly and efficiently at the protocol-level is now in, and so I've landed all of this now, which included:

* Rebasing `humphd/bramble` onto `adobe/brackets/master` (we are now at https://github.com/adobe/brackets/commit/873e8d5ca7a10b878b5fa09c930b677c80c54096)
* Reverting the patch for copy-paste fixes in Live Dev in https://github.com/adobe/brackets/issues/10634
* Merging @busykai's work in `kai/fix-5656-live-dev` and `kai/fix-10821-ld-allow-reload-in-browser`

Everything's working nicely now, as far as I can tell.  I also pushed `dist/` up to my `gh-pages` branch so people can test if they want:

* http://humphd.github.io/brackets/dist/ (our stripped down UI for use in Thimble)
* http://humphd.github.io/brackets/dist/?ui=1 (full Brackets UI in case you need it)

I'm going to close this and we can file follow-up bugs as we find them.  Thanks for all the help.
