### ISSUE TITLE
Make thimble load brackets from another domain

### ISSUE THREAD

**Issue by sedge** [humphd/brackets#107]
This is important to protect the security of webmaker's ecosystem and its users. To accomplish this, we'd need to: 

* [x] Add configuration options that allow us to specify which domains can send postMessages to and from the thimble and brackets domains
* [x] Reconfigure the brackets iframe to load from an external domain
* [x] Add a grunt task that would serve brackets from a separate local domain while running thimble as normal
* [x] Add a hook somewhere to automatically deploy the latest brackets code to the S3 bucket being used as https://mozillathimblelivepreview.net

**Comment by humphd** [comment]
It's also worth adding that we're eventually going to want to be able to load from the S3 bucket at https://mozillathimblelivepreview.net/ and ideally with a sub dir (maybe https://mozillathimblelivepreview.net/bramble) in order to not break current Thimble.  This includes figuring out the TravisCI magic we need for publishing our Bracket's `dist/` folder automagically.

cc @jbuck

**Comment by sedge** [comment]
Updated.

**Comment by humphd** [comment]
I think I'd clarify that we only need to start/run a static server for local development, and we might even want to avoid that, and just let people run their own, rather than making the Thimble stuff overly complex.

That is, for local dev you'd grab the branch of Brackets that you want, and run your own static web server in the `dist/` dir, then point your env at that URL (http://localhost:8888 or whatever).

**Comment by humphd** [comment]
WIP in https://github.com/sedge/thimble.webmaker.org/pull/18

**Comment by sedge** [comment]
Closed with https://github.com/mozilla/thimble.webmaker.org/issues/474
