### ISSUE TITLE
Prefer blob URLs from cache whenever possible

### ISSUE THREAD

**Issue by gideonthomas** [humphd/brackets#138]
This bug has two parts:
* Currently, in our html rewriter code [here](https://github.com/humphd/brackets/blob/bramble/src/filesystem/impls/lib/HTMLRewriter.js#L46-L52) and [here](https://github.com/humphd/brackets/blob/bramble/src/filesystem/impls/lib/HTMLRewriter.js#L83-L98), we fetch from disk and then generate a blob url. Instead, we should try to check if one already exists for that path in cache and use it and if not, only then generate a new one.
* In our css rewriter code, for now whenever we encounter a `url("path to file")` we replace it with the contents of that file. Instead, we should check for a blob url for that path in cache and use that instead, otherwise, we should generate a new one and use it instead of copy/pasting the entire contents of that file. 

cc @humphd

**Comment by humphd** [comment]
I *think* that if there isn't a cached BLOB URL already existing, it means that `writeFile()` was never called for that path, and therefore trying to re-read it isn't going to produce anything new.  One interesting side-effect of doing this change is that it would turn the process into something synchronous, since it's just going to be O(1) lookups.

**Comment by humphd** [comment]
Assigning to @K-LV, since I want this done in conjunction with #162.
