### ISSUE TITLE
Hook up the reload button in thimble to reload the livedev preview.

### ISSUE THREAD

**Issue by AJDBenner** [humphd/brackets#146]
Right now clicking on the reload button in thimble does nothing. We want to make the button reload the rendered html document when pushed.

**Comment by KeniMorri** [comment]
This feature was proposed by, well, me a while ago, but we didn't need it back then. You should bring this up with @humphd to see how you should proceed with this. If all we wanted to do was refresh the content then:

1. Hook up reload button to executeCommand inside Bramble Proxy
2. Make a new command inside executeCommand to send a reload command to brackets-livedev
3. Add another command to receive inside the listener
4. Add a new public method in iframe browser in order to refresh

**Comment by AJDBenner** [comment]
[This](https://github.com/humphd/brackets-browser-livedev/pull/44) PR and [this](https://github.com/sedge/thimble.webmaker.org/pull/21) are a WIP to fix this issue.
