### ISSUE TITLE
See if we can learn from this paper

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#154]
http://www.andreaforte.net/ParkICER2013.pdf is an interesting read, and it makes me wonder if there is anything we could learn from it and/or implement in Bramble to help those learning web dev.

**Comment by KeniMorri** [comment]
I'm not going to assign this to myself, but I will give it a read when I have time

**Comment by KeniMorri** [comment]
Skimming through this article, they bring up.
Their editor seems pretty straight forward, with HTML + CSS + Preview,
- I was thinking that with our new detachable preview pane that it would be possible to have a layout similar to such:
![screenshot 2015-04-17 10 28 36](https://cloud.githubusercontent.com/assets/1750230/7203946/887c0afc-e4ec-11e4-81fa-49cc9778b416.png)

So that the user doesn't need to waste time going back and forth through files

- Another thing we should look into adding is possibly a css hinter
-

More updates soon

**Comment by humphd** [comment]
@flukeout has been doing a bunch of this research on his own, and is/will file bugs in Thimble.  I'm going to close this here and we'll deal with things in new bugs.
