### ISSUE TITLE
Remove unused languages

### ISSUE THREAD

**Issue by JordanTheriault** [humphd/brackets#282]
There is the option to switch the editing mode to Markdown, but it will not render it in markdown. This doesn't seem to match the scope of the app, so it may be worth while to simply remove the unused/irrelevant options.

![screenshot 2015-05-14 15 45 27](https://cloud.githubusercontent.com/assets/5931078/7640343/b3ca6b26-fa50-11e4-978f-921df6fea11c.png)

**Comment by sedge** [comment]
My vote is that we scrap that entire dropdown and automatically switch based on the file type.

We could write an extension to make this manual for advanced users.

**Comment by humphd** [comment]
The way to deal with this is probably to create a `BasicUI` extension, which hides the entire status bar.  I strongly suspect the mobile preview, and detach preview, need to move out of the status bar anyway.

A side note: this is a very useful menu, since it lets you enable a mode for a file type that doesn't match the known extension list.  I wouldn't want to remove it on its own, but hiding for beginners probably makes sense.  Maybe morph this bug into creating a new extension for beginners.

**Comment by sedge** [comment]
I like the idea of hiding it vs removing. What if we wrote an extension that just controls UI, and let thimble dictate what's shown through querystring (ala extensions)? That seems to be the most flexible way moving forward and it could be simple at first.

**Comment by humphd** [comment]
I don't think you want to introduce too many separate configuration axes.  We already have separate extensions, and modes will let us bundle extensions for convenience.  Our UI isn't so complex beyond that that we need a separate way to also specify those bits; also, I think it makes compatibility with extensions harder, if we also are adding/removing bits of UI per extension run.

I'd still suggest we rely on an extension (or extensions) that turn off the bits of the full UI we don't want for basic mode(s).

**Comment by sedge** [comment]
That's sound reasoning.

**Comment by humphd** [comment]
We don't show the status bar anymore, this can be closed.
