### ISSUE TITLE
Replace extension dependencies in `node_modules` with submodule equivalents

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#324]
Is the Travis/Gruntfile build stuff not doing the right thing, and missing deps?

```
GET https://mozillathimblelivepreview.net/bramble/node_modules/slowparse/locale/en_US.json 404
GET "https://mozillathimblelivepreview.net/bramble/node_modules/slowparse/locale/en_US.json".text.get
[Extension] failed to load /bramble/dist/extensions/extra/HTMLHinter - Error: /bramble/dist/extensions/extra/HTMLHinter/../../../../node_modules/slowparse/locale/en_US.json HTTP status: 404
```

**Comment by humphd** [comment]
NOTE: this was loading the following URL: https://bramble.mofostaging.net/?enableExtensions=HTMLHinter

**Comment by humphd** [comment]
Seems to work fine locally in both `src/` and `/dist` builds.

**Comment by humphd** [comment]
Two problems:
* we don't copy `node_modules/` to `dist/`
* we have our path expansion wrong for the `src/` vs. `dist/` case here https://github.com/humphd/brackets/blob/bramble/src/extensions/extra/HTMLHinter/parser.js#L7-L9

To get the `node_modules/` into `dist/` you can do this:

```diff
diff --git a/Gruntfile.js b/Gruntfile.js
index 9cc665b..405b584 100644
--- a/Gruntfile.js
+++ b/Gruntfile.js
@@ -150,6 +150,15 @@ module.exports = function (grunt) {
                             'thirdparty/text/*.js'
                         ]
                     },
+                    /* add node_modules from the root */
+                    {
+                        expand: true,
+                        dest: 'dist/',
+                        cwd: './',
+                        src: [
+                            'node_modules/**/*'
+                        ]
+                    },
                     /* styles, fonts and images */
                     {
                         expand: true,
```

Getting the paths right is left to the reader.

**Comment by sedge** [comment]
@humphd We see the problem in deployment when accessing `/dist`, but it would exist for `/src` too. Basically, if we are copying `node_modules` then we have to copy it to both `/src` and `/dist` in order to write the paths once and have them work in both places. 

I propose that we move third-party extension dependencies to `src/thirdparty` using submodules, or copying stuff wholesale, so that we skip this problem entirely. That would make sure any submodule using that dep would load it from the same place.

Alternatively, it would be nice to use npm. That would require creating a grunt task to install those deps from a `package.json` file in `src/thirdparty`.

What do you think?

**Comment by humphd** [comment]
Agree, make it work using `src/thirdparty` and submodules.  That's the Brackets way.
