### ISSUE TITLE
QuickDocs using MDN

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#328]
https://twitter.com/humphd/status/604107003456294912

Let's see if we can hijack the WebPlatformDocs/QuickDocs stuff to use this in a new extension.  Make sure we check for existing code we can steal in https://brackets-registry.aboutweb.com/ (search for MDN).

**Comment by JordanTheriault** [comment]
There is not an existing Brackets extension which can do this. However, WebPlatformDocs can be altered to retrieve JSON from MDN using $json.

**Comment by JordanTheriault** [comment]
@humphd The current WebDocs uses a static JSON library of property descriptions scraped from WebDocs, and simply has links to each page. This method is fast, but is the vision for this, to grab the most current information from the MDN website while the user is using the extension?

**Comment by humphd** [comment]
I think we should probably write a little node script or something to download the latest JSON file from MDN, and we can run it every so often; but let's cache the JSON in the extension, and XHR it when we need it.  Or do you think we should just XHR it from MDN on demand?  Either way we need to XHR it on first use.

**Comment by JordanTheriault** [comment]
Two ways:
1. Scrape MDN, and simply add it in as Brackets with name, description, and URL. XHR from our JSON file.
2. XHR from MDN based on the current prop name.

The question really is - how often does the description for these change? Probably not often, and in that case scraping MDN and providing URLs may be the best method of achieving this.

**Comment by humphd** [comment]
What does "scrape MDN" mean?

**Comment by JordanTheriault** [comment]
Unless we recycle the [WebPlatformDocs JSON file](https://github.com/MarcelGerber/brackets/blob/html-docs/src/extensions/default/WebPlatformDocs/html.json) and change the URLs, we will need to scrape MDN for the prop names and descriptions, as well as the URL. [This has been done in 2012](https://github.com/toolness/Hacktionary). Because MDN doesn't provide a JSON file with all the prop names and a short description, something will need to be written to generate it.

**Comment by JordanTheriault** [comment]
Pull request pending at #343
