### ISSUE TITLE
Reduce distribution size and load times for Bramble

### ISSUE THREAD

**Issue by gideonthomas** [humphd/brackets#66]
There are a couple of things to do in this bug:

* There is a lot that can be removed in Thimble that Brackets does instead
* Figure out issues with Firefox loading a larger file size than Chrome
* Follow up pruning of code that we will not use in Brackets

@sedge @humphd any thing to add?

**Comment by sedge** [comment]
When thimble is being loaded, there's a number of requests (~70!) that just flat out fail. These need to be addressed.

**Comment by humphd** [comment]
Hilariously, Thimble is loading jquery-ui (426K), jquery (262K), and other scripts in unminified form, which is adding a ton of heft.  So that will help a lot.  I'll fix upstream.  We *also* load jquery.min.

Other things not minified for some reason, and being loaded by friendlycode and/or brackets:

* require.js (we also load the minified version)
* slowparse.js (we also load this *twice* in HTMLHinter and friendlycode)

Because the extensions are bundled into a single module and minified, we're also loading things many times (e.g., the requirejs text plugin gets loaded at least 6 times).

Also, the webmakerLogin.min.js is 225K, which is a big hard to swallow.  I'll see if I can get that shrunk down upstream too.

So there's some pretty quick wins here.  I bet we'll find other things we can kill off, since we don't need to duplicate some functionality across the various iframes/repos.

**Comment by humphd** [comment]
Filed/fixed https://github.com/mozilla/thimble.webmaker.org/pull/472 to fix minifying CDN resources in Thimble.

**Comment by humphd** [comment]
Filed https://github.com/mozilla/webmaker-login-ux/issues/167 on webmakerLogin.min.js

**Comment by humphd** [comment]
The font loading Brackets is doing adds a lot of weight on the wire.  Pomax filed a bug upstream on this, https://github.com/adobe/brackets/issues/10680

**Comment by humphd** [comment]
Filed #78 on reducing the size of fonts we load, which gets us down to the sub-600K level.

**Comment by humphd** [comment]
Landed #74, which helps a bunch.

**Comment by AJDBenner** [comment]
[This](https://github.com/sedge/thimble.webmaker.org/pull/11) PR will help reduce the size by about 100K before gzip

**Comment by AJDBenner** [comment]
[This](https://github.com/sedge/thimble.webmaker.org/pull/16) PR helps reduce the size.

**Comment by humphd** [comment]
The only concrete thing left is the font switch, which is #78, so I'm going to close this bug.  We made a huge dent, nice work!
