### ISSUE TITLE
Move away from Source Code Pro web fonts in favour of system fonts

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#78]
Brackets loads 300K+ of (gzipped) web fonts, and switching over to using system fonts is a pretty big saving.  @peterflynn wisely suggested moving away from web fonts in https://github.com/adobe/brackets/issues/10680#issuecomment-77119232, suggesting we use a `font-family` of `"Menlo Regular", Consolas, Inconsolata, "Vera Sans", "Lucida Console", Courier, fixed;`.  I did a quick test of this, and with other size optimization things we're doing, it gets us down to ~600K (gzipped), which is pretty good for a complete desktop editor, filesystem, etc.

I'm trying to decide the best way to make this switch, specifically how to do it with the least disruption to Brackets' code.  The bulk of the Brackets font stuff is in https://github.com/adobe/brackets/blob/ae17456a596965a1247b79ddb82c6e1518bc6e5e/src/styles/brackets_fonts.less.  However, looking around, there are a bunch of places that assume that either SourceSansPro or SourceCodePro have been defined, and therefore downloaded:

* https://github.com/adobe/brackets/search?utf8=%E2%9C%93&q=sourcesanspro&type=Code
* https://github.com/adobe/brackets/search?utf8=%E2%9C%93&q=sourcecodepro&type=Code

@Pomax and/or @peterflynn, what's the best way to do this for the browser case?  It's too bad that all the uses of `font-family: SourceSansPro;` and `font-family: SourceCodePro;` in the less files weren't being done with variables, `font-family: @SourceSansPro;` or the like.

**Comment by peterflynn** [comment]
I'd say references to "SourceSansPro" should be changed to the existing LESS var `@sansFontFamily`, and we should introduce a similar variable for the code font -- that's an easy change to take upstream.  Then the only diff your fork would have is changing the definition of those two vars.

For cleanliness you could also comment out / remove the `@font-face` declarations, but I'm pretty sure browsers don't start loading those unless they're referenced somewhere -- so that's probably not strictly necessary.

**Comment by Pomax** [comment]
one thing that we can do specifically here, is check the subsetting bits for these fonts - I suspect they're set to allow subsetting, which would allow us to run a proxy for serving the webfonts with only—say—the Latin blocks, drastically bringing down the resource size.

**Comment by AJDBenner** [comment]
https://github.com/humphd/brackets/pull/110 fixes this issue
